#
# This is all of the combat messages used by combat.c
# Note: all %d values will be filled with a number greater than 1
#
# Truly Generic strings (no need for gender/number issues)
#
{100}{}{Voce precisa de %d pontos de acao.}
{101}{}{Sem municao.}
{102}{}{Alvo fora do alcance.}
{103}{}{O combate nao pode acabar enquanto existir criaturas hostis proximas.}
{104}{}{Seu alvo/mira esta bloqueado.}
{105}{}{Voce nao pode usar armas com ambos os braços paralisados.}
{106}{}{Voce nao pode usar armas de duas maos com um braço aleijado.}
{107}{}{Voce nao esta forte o suficiente para usar esta arma corretamente.}
{108}{}{ e }
#
# Combat Flag Strings (all of these happen to you, the MALE player)
#
{200}{}{nocauteado}
{201}{}{derrubado}
{202}{}{aleijou sua perna esquerda}
{203}{}{aleijou sua perna direita}
{204}{}{aleijou seu braço esquerdo}
{205}{}{aleijou seu braço direito}
{206}{}{cego}
{207}{}{foi mortos}
{208}{}{hit}
{209}{}{critico}
{210}{}{em chamas}
{211}{}{teve sua armadura ignorada}
{212}{}{sua arma explodiu}
{213}{}{sua arma foi destruida}
{214}{}{sua arma caiu}
{215}{}{perdeu seu proximo turno}
{216}{}{se acertou}
{217}{}{perdeu o resto da sua municao}
{218}{}{disparou um tiro fraco}
{219}{}{feriu-se}
{220}{}{golpe aleatorio}
{221}{}{aleijou um membro aleatorio}
{222}{}{feriu-se com fragmentos}
#
# Combat Flag Strings (all of these happen to you, the FEMALE player)
#
{250}{}{nocauteada}
{251}{}{derrubada}
{252}{}{aleijou sua perna esquerda}
{253}{}{aleijou sua perna direita}
{254}{}{aleijou seu braço esquerdo}
{255}{}{aleijou seu braço direito}
{256}{}{cega}
{257}{}{foi mortos}
{258}{}{hit}
{259}{}{critico}
{260}{}{em chamas}
{261}{}{teve sua armadura ignorada}
{262}{}{sua arma explodiu}
{263}{}{sua arma foi destruida}
{264}{}{sua arma caiu}
{265}{}{perdeu seu proximo turno}
{266}{}{se acertou}
{267}{}{perdeu o resto da sua municao}
{268}{}{disparou um tiro fraco}
{269}{}{feriu-se}
{270}{}{golpe aleatorio}
{271}{}{aleijou um membro aleatorio}
{272}{}{feriu-se com fragmentos}
#
# Combat Flag Strings (all of these happen to a male)
#
{300}{}{nocauteado}
{301}{}{derrubado}
{302}{}{aleijou sua perna esquerda}
{303}{}{aleijou sua perna direita}
{304}{}{aleijou seu braço esquerdo}
{305}{}{aleijou seu braço direito}
{306}{}{cego}
{307}{}{foi mortos}
{308}{}{hit}
{309}{}{critico}
{310}{}{em chamas}
{311}{}{teve sua armadura ignorada}
{312}{}{sua arma explodiu}
{313}{}{sua arma foi destruida}
{314}{}{sua arma caiu}
{315}{}{perdeu seu proximo turno}
{316}{}{se acertou}
{317}{}{perdeu o resto da sua municao}
{318}{}{disparou um tiro fraco}
{319}{}{feriu-se}
{320}{}{golpe aleatorio}
{321}{}{aleijou um membro aleatorio}
{322}{}{feriu-se com fragmentos}
#
# Combat Flag Strings (all of these happen to a female)
#
{400}{}{nocauteada}
{401}{}{derrubada}
{402}{}{aleijou sua perna esquerda}
{403}{}{aleijou sua perna direita}
{404}{}{aleijou seu braço esquerdo}
{405}{}{aleijou seu braço direito}
{406}{}{cega}
{407}{}{foi mortos}
{408}{}{hit}
{409}{}{critico}
{410}{}{em chamas}
{411}{}{teve sua armadura ignorada}
{412}{}{sua arma explodiu}
{413}{}{sua arma foi destruida}
{414}{}{sua arma caiu}
{415}{}{perdeu seu proximo turno}
{416}{}{se acertou}
{417}{}{perdeu o resto da sua municao}
{418}{}{disparou um tiro fraco}
{419}{}{feriu-se}
{420}{}{golpe aleatorio}
{421}{}{aleijou um membro aleatorio}
{422}{}{feriu-se com fragmentos}
#
# Miscellaneous combat messages (all of these happen to you, the male player)
# Note: the first  %s will be replaced by the value of line 506, which
#     should be the language's equivalent to 2nd person male singular,
#     which is "You" in English. The first letter of line 506 should
#     be capitalized, since it will start a sentence.
#    the second  %s (if there is one) is the hit location, which
#     will be a string from the section Hit Locations starting
#     in the 1000's in this file, with the exception of line 509
#     where the second  %s is the name of another creature
{506}{}{Voce}
{509}{}{Oops!  %s foi atingido em vez de  %s!}
{511}{}{  %s foi criticamente atingido em  %s para %d pontos de vida}
{512}{}{  %s foi atingido em  %s para %d pontos de vida}
{513}{}{  %s foi atingido por %d pontos de vida}
{514}{}{  %s perdeu gravemente}
{515}{}{  %s perderam}
{520}{}{  %s foi criticamente atingido por %de pontos de vida}
{521}{}{  %s foi criticamente atingido em  %s para 1 ponto de acerto}
{522}{}{  %s foi atingido em  %s para 1 ponto de acerto}
{523}{}{  %s foi atingido por 1 ponto de acerto}
{524}{}{  %s foi criticamente atingido por 1 ponto de acerto}
{525}{}{  %s foi criticamente atingido em  %s sem danos}
{526}{}{  %s foi atingido em  %s sem danos}
{527}{}{  %s foi atingido sem danos}
{528}{}{  %s foi criticamente atingido por nenhum dano}
{533}{}{  %s perdeu e levou 1 ponto de acerto}
{534}{}{  %s perdeu e levou %d pontos de vida}
#
# Miscellaneous combat messages (all of these happen to you, the female player)
# Note: the first  %s will be replaced by the value of line 556, which
#     should be the language's equivalent to 2nd person female singular,
#     which is "You" in English. The first letter of line 556 should
#     be capitalized, since it will start a sentence.
#    the second  %s (if there is one) is the hit location, which
#     will be a string from the section Hit Locations starting
#     in the 1000's in this file, with the exception of line 559
#     where the second  %s is the name of another creature
{556}{}{Voce}
{559}{}{Ops!  %s foi atingido em vez de  %s!}
{561}{}{ %s foi criticamente atingido em  %s para %d pontos de vida}
{562}{}{ %s foi atingido em  %s para %d hit points}
{563}{}{ %s foi atingido para %d pontos de vida}
{564}{}{ %s perdeu gravemente}
{565}{}{ %s perdeu}
{570}{}{ %s foi criticamente atingido por %d pontos de vida}
{571}{}{ %s foi criticamente atingido em  %s para 1 ponto de acerto}
{572}{}{ %s foi atingido em  %s para 1 ponto de acerto}
{573}{}{ %s foi atingido por 1 ponto de acerto}
{574}{}{ %s foi criticamente atingido por 1 ponto de acerto}
{575}{}{ %s foi criticamente atingido em  %s sem danos}
{576}{}{ %s foi atingido em  %s sem danos}
{577}{}{ %s foi atingido sem danos}
{578}{}{ %s foi criticamente atingido por nenhum dano}
{583}{}{ %s perdeu e levou 1 ponto de acerto}
{584}{}{ %s perdeu e levou %d pontos de vida}
#
# Miscellaneous combat messages (all of these happen to a male)
# Note: the first  %s is the name of the male creature
#    the second  %s (if there is one) is the hit location, which
#     will be a string from the section Hit Locations starting
#     in the 1000's in this file, with the exception of line 609
#     where the second  %s is the name of another creature
#
{608}{}{Oops!  %s foi atingido em vez de voce!}
{609}{}{Oops!  %s foi atingido em vez de  %s!}
{611}{}{  %s foi criticamente atingido  %s para %d pontos de vida}
{612}{}{  %s foi atingido em  %s para %d pontos de vida}
{613}{}{  %s foi atingido por %d pontos de vida}
{614}{}{  %s perdeu criticamente}
{615}{}{  %s perdeu}
{620}{}{  %s foi criticamente atingido por %d pontos de vida}
{621}{}{  %s foi criticamente atingido  %s por 1 ponto de acerto}
{622}{}{ %s foi atingido em %s para 1 ponto de acesso}
{623}{}{ %s foi atingido por 1 ponto de acerto}
{624}{}{ %s foi atingido criticamente por 1 ponto de acesso}
{625}{}{ %s foi gravemente atingido em %s sem danos}
{626}{}{ %s foi atingido em %s sem danos}
{627}{}{ %s foi atingido por nenhum dano}
{628}{}{ %s foi gravemente atingido por nenhum dano}
{633}{}{ %s criticamente perdeu e teve 1 ponto de acerto}
{634}{}{ %s criticamente perdeu e levou% d pontos de vida}
#
# Miscellaneous combat messages (all of these happen to a female)
# Note: the first  %s is the name of the female creature
#    the second  %s (if there is one) is the hit location, which
#     will be a string from the section Hit Locations starting
#     in the 1000's in this file, with the exception of line 709
#     where the second  %s is the name of another creature
#
{708}{}{Ops!  %s foi atingido em vez de você!}
{709}{}{Ops!  %s foi atingido em vez de %s!}
{711}{}{ %s foi gravemente atingido em %s para% d pontos de vida}
{712}{}{ %s foi atingido em %s para% d pontos de vida}
{713}{}{ %s foi atingido para% d hit points}
{714}{}{ %s criticamente perdeu}
{715}{}{ %s perdeu}
{720}{}{ %s foi gravemente atingido por% d pontos de vida}
{721}{}{ %s foi atingido criticamente em %s para 1 ponto de acesso}
{722}{}{ %s foi atingido em %s para 1 ponto de acerto}
{723}{}{ %s foi atingido por 1 ponto de acesso}
{724}{}{ %s foi gravemente atingido por 1 ponto de acerto}
{725}{}{ %s foi gravemente atingido em %s sem danos}
{726}{}{ %s foi atingido em %s sem danos}
{727}{}{ %s foi atingido sem nenhum dano}
{728}{}{ %s foi gravemente atingido por nenhum dano}
{733}{}{ %s criticamente perdeu e teve 1 ponto de acerto}
{734}{}{ %s criticamente perdeu e levou% d pontos de vida}
#
# Hit Locations (by art_num alias)
#
# regular humans
#
{1110}{}{a cabeça}
{1111}{}{o braço esquerdo}
{1112}{}{o braço direito}
{1113}{}{o torso}
{1114}{}{a perna direita}
{1115}{}{a perna esquerda}
{1116}{}{os olhos}
{1117}{}{a virilha}
{1118}{}{não chamado}
#
# Brahmin (Mutant 2-Headed Cows)
#
{1150}{}{a cabeça}
{1151}{}{a parte traseira esquerda}
{1152}{}{a parte traseira direita}
{1153}{}{o torso}
{1154}{}{a perna anterior direita}
{1155}{}{a perna anterior esquerda}
{1156}{}{os olhos}
{1157}{}{o udder}
{1158}{}{não chamado}
#
# dogs
#
{1160}{}{a cabeça}
{1161}{}{a hindleg}
{1162}{}{a hindleg}
{1163}{}{o corpo}
{1164}{}{a parte dianteira}
{1165}{}{a parte dianteira}
{1166}{}{os olhos}
{1167}{}{a virilha}
{1168}{}{não chamado}
#
# Mr. Handy
#
{1170}{}{a CPU}
{1171}{}{o manipulador}
{1172}{}{o manipulador}
{1173}{}{o quadro}
{1174}{}{o motivador}
{1175}{}{o motivador}
{1176}{}{os sensores}
{1177}{}{o regulador}
{1178}{}{não chamado}
#
# Super Mutants
#
{1180}{}{a cabeça}
{1181}{}{o braço esquerdo}
{1182}{}{o braço direito}
{1183}{}{o torso}
{1184}{}{a perna direita}
{1185}{}{a perna esquerda}
{1186}{}{os olhos}
{1187}{}{a virilha}
{1188}{}{não chamado}
#
# Mole-Rat
#
{1190}{}{a cabeça}
{1191}{}{a pata esquerda}
{1192}{}{a pata direita}
{1193}{}{o corpo}
{1194}{}{a perna direita}
{1195}{}{a perna esquerda}
{1196}{}{os olhos}
{1197}{}{a virilha}
{1198}{}{não chamado}
#
# big humans and mutants
#
{1210}{}{a cabeça}
{1211}{}{o braço esquerdo}
{1212}{}{o braço direito}
{1213}{}{o torso}
{1214}{}{a perna direita}
{1215}{}{a perna esquerda}
{1216}{}{os olhos}
{1217}{}{a virilha}
{1218}{}{não chamado}
#
# Radscorpion
#
{1220}{}{a cabeça}
{1221}{}{a cauda}
{1222}{}{a garra}
{1223}{}{a carapaça}
{1224}{}{as pernas dianteiras}
{1225}{}{as patas traseiras}
{1226}{}{os olhos}
{1227}{}{o cérebro}
{1228}{}{não chamado}
#
# Floater
#
{1230}{}{a cabeça}
{1231}{}{a boca}
{1232}{}{a boca anterior}
{1233}{}{o corpo}
{1234}{}{o saco flutuante}
{1235}{}{a cauda}
{1236}{}{o gânglio}
{1237}{}{o ovipositor}
{1238}{}{não chamado}
#
# masrat? a rat perhaps?
#
{1240}{}{a cabeça}
{1241}{}{a pata esquerda}
{1242}{}{a pata direita}
{1243}{}{o corpo}
{1244}{}{a perna direita}
{1245}{}{a perna esquerda}
{1246}{}{os olhos}
{1247}{}{a virilha}
{1248}{}{não chamado}
#
# Centaur
#
{1250}{}{a cabeça}
{1251}{}{o braço esquerdo}
{1252}{}{o braço direito}
{1253}{}{o corpo}
{1254}{}{a perna direita}
{1255}{}{a perna esquerda}
{1256}{}{os olhos}
{1257}{}{a virilha}
{1258}{}{não chamado}
#
# human midgets and children
#
{1270}{}{a cabeça}
{1271}{}{o braço esquerdo}
{1272}{}{o braço direito}
{1273}{}{o torso}
{1274}{}{a perna direita}
{1275}{}{a perna esquerda}
{1276}{}{os olhos}
{1277}{}{a virilha}
{1278}{}{não chamado}
#
# Overseer
#
{1460}{}{a cabeça}
{1461}{}{o braço esquerdo}
{1462}{}{o braço direito}
{1463}{}{o torso}
{1464}{}{a perna direita}
{1465}{}{a perna esquerda}
{1466}{}{os olhos}
{1467}{}{a virilha}
{1468}{}{não chamado}
#
# Gizmo
#
{1490}{}{a cabeça}
{1491}{}{o braço esquerdo}
{1492}{}{o braço direito}
{1493}{}{o torso}
{1494}{}{a perna direita}
{1495}{}{a perna esquerda}
{1496}{}{os olhos}
{1497}{}{a virilha}
{1498}{}{não chamado}
#
# The Master!
#
{1500}{}{a cabeça}
{1501}{}{???}
{1502}{}{???}
{1503}{}{o quadro}
{1504}{}{???}
{1505}{}{???}
{1506}{}{os olhos}
{1507}{}{a CPU}
{1508}{}{não chamado}
#
# Death Claw
#
{1510}{}{a cabeça}
{1511}{}{o braço esquerdo}
{1512}{}{o braço direito}
{1513}{}{o torso}
{1514}{}{a perna direita}
{1515}{}{a perna esquerda}
{1516}{}{os olhos}
{1517}{}{a virilha}
{1518}{}{não chamado}
#
# Mantis
#
{1520}{}{a cabeça}
{1521}{}{a perna de raptorial}
{1522}{}{a perna raptorial}
{1523}{}{o abdômen}
{1524}{}{as pernas}
{1525}{}{as asas}
{1526}{}{os olhos}
{1527}{}{the metathorax}
{1528}{}{não chamado}
#
# Robobrain
#
{1530}{}{a CPU}
{1531}{}{o manipulador}
{1532}{}{o manipulador}
{1533}{}{o quadro}
{1534}{}{o motivador}
{1535}{}{o motivador}
{1536}{}{os sensores}
{1537}{}{o regulador}
{1538}{}{não chamado}
#
# Eyeball (Robot)
#
{1540}{}{a CPU}
{1541}{}{o manipulador}
{1542}{}{o manipulador}
{1543}{}{o quadro}
{1544}{}{o motivador}
{1545}{}{o motivador}
{1546}{}{os sensores}
{1547}{}{o regulador}
{1548}{}{não chamado}
#
# Mutant Pig Rat (small Mole-Rat)
#
{1550}{}{a cabeça}
{1551}{}{a pata esquerda}
{1552}{}{a pata direita}
{1553}{}{o corpo}
{1554}{}{a perna direita}
{1555}{}{a perna esquerda}
{1556}{}{os olhos}
{1557}{}{a virilha}
{1558}{}{não chamado}
#
# Deathclaw Egg
#
{1580}{}{o casca}
{1581}{}{o casca}
{1582}{}{o casca}
{1583}{}{o casca}
{1584}{}{o casca}
{1585}{}{o casca}
{1586}{}{o casca}
{1587}{}{o casca}
{1588}{}{não chamado}

#
# Critical Hit Messages
#
# 5000 series - men (including generics)
#
{5000}{}{e realmente dói}
{5001}{}{. Uma ferida grave é infligida}
{5002}{}{sem defesa de armadura}
{5003}{}{. O ataque prejudicial o deixa inconsciente}
{5004}{}{. O golpe bate-o no chão}
{5005}{}{. O forte golpe na cabeça o afasta}
{5006}{}{. O ataque esmaga o templo. Boa noite, Gracie
{5007}{}{, a morte é instantânea}
{5008}{}{, causando cotovelo de tenista severo}
{5009}{}{, empurrando o braço para fora do caminho}
{5010}{}{, deixando uma grande hematoma}
{5011}{}{, danificando o braço esquerdo}
{5012}{}{, deixando o braço esquerdo pendurado pela pele}
{5013}{}{. Esse braço agora parece um tronco sangrento}
{5014}{}{, deixando um braço direito aleijado}
{5015}{}{. Seu braço direito é pulverizado por este poderoso golpe}
{5016}{}{em um golpe vigoroso}
{5017}{}{soprando a armadura}
{5018}{}{, infligindo uma ajuda adicional de dano}
{5019}{}{sem armadura, batendo o combatente no chão}
{5020}{}{derrubando o ar, ele cai no chão fora da luta}
{5021}{}{. Infelizmente, sua espinha agora é claramente visível da frente}
{5022}{}{colocando uma grande dor na perna}
{5023}{}{, batendo-o no chão como um boliche em um jogo de liga}
{5024}{}{, rolando-o e paralisando essa perna}
{5025}{}{, esmagando o joelho na próxima cidade. Ele cai}
{5026}{}{. A dor intensa de ter uma perna removida faz com que ele saia}
{5027}{}{infligindo alguma dor extra}
{5028}{}{causando cegueira, desafortunadamente para ele}
{5029}{}{, e sem proteção lá, causando dores graves}
{5030}{}{, e cegando-o com um golpe impressionante}
{5031}{}{. A perda de olho é demais para ele, e ele cai no chão
{5032}{}{, infelizmente, ele está muito ocupado sentindo a onda de ar no cérebro para notar a morte se aproximando}
{5033}{}{. Ouch! Isso teve que machucar
{5034}{}{, e ele não está usando uma xícara, tampouco}
{5035}{}{e sem proteção, ele cai, gemendo em agonia}
{5036}{}{. A dor é demais para ele e ele colapsa como um pano}
{5037}{}{. Ele murmura "Mãe", enquanto seus olhos se roçam na parte de trás da cabeça dele
#
# series 5100 - women
#
{5100}{}{e realmente machuca}
{5101}{}{. Uma ferida grave é infligida}
{5102}{}{sem armadura}
{5103}{}{. O ataque prejudicial acha inconsciente
{5104}{}{. O golpe bate na terra
{5105}{}{. O forte golpe na cabeça a toca
{5106}{}{. O ataque esmaga seu templo. Boa noite, Gracie
{5107}{}{, a morte é instantânea}
{5108}{}{, causando coto de tenista severo}
{5109}{}{, empurrando o braço para fora do caminho}
{5110}{}{, deixando uma grande hematoma}
{5111}{}{, danificando o braço esquerdo}
{5112}{}{. O braço esquerdo está mal preso em seu ombro}
{5113}{}{. Esse braço agora parece um tronco sangrento}
{5114}{}{, deixando um braço direito aleijado}
{5115}{}{. Seu braço direito é transformado em hambúrguer pelo golpe.
{5116}{}{em um golpe poderoso}
{5117}{}{piercing através de suas defesas}
{5118}{}{, infligindo uma ajuda adicional de dano}
{5119}{}{sem armadura, batendo a lutadora feminina no chão}
{5120}{}{derrubando o ar, ela cai no chão}
{5121}{}{. Infelizmente, seus principais órgãos foram expostos à luz}
{5122}{}{colocando uma grande dor na perna}
{5123}{}{, derrubando-a como uma data ruim e cega}
{5124}{}{, derrubando-a e incapacitando essa perna}
{5125}{}{, esmagando o joelho na próxima cidade. Ela leva a trilha rápida para o chão
{5126}{}{. Ela grita com dor da perna quebrada
{5127}{}{infligindo alguma dor extra}
{5128}{}{causando cegueira. Ela faz caretas}
{5129}{}{, e sem proteção lá, causando dores graves}
{5130}{}{. A ferida causa cegueira severa, como se houvesse algum outro tipo}
{5131}{}{. Ela desmaia do ataque cegador}
{5132}{}{, infelizmente, ela não consegue rezar a seus deuses antes de encontrá-los}
{5133}{}{. Ela o leva como um homem. Ou seja, dói}
{5134}{}{, batendo-a no chão}
{5135}{}{. Seus dias fecundos estão com problemas quando ela colapsa em uma pilha mole}
#
# series 5200 - children
#
{5200}{}{. A criança começa a chorar}
{5201}{}{. Inconsciente, a criança pequena cai
{5202}{}{. Ouchie!}
{5203}{}{. O golpe é verdadeiro, e a criança é batida inconsciente}
{5204}{}{, esmagando a criança pequena como um pano macio}
{5205}{}{. O braço esquerdo desta criança agora tem um owie
{5206}{}{, jogando a criança pequena fora do equilíbrio}
{5207}{}{, quebrando esse braço com uma pressão alta. Algumas lágrimas sérias começam a fluir}
{5208}{}{, encaixando facilmente esse braço como um pequeno pedaço de doce}
{5209}{}{. O braço direito começa a inchar, como um balão}
{5210}{}{e começa a chorar}
{5211}{}{em um ponto sensível}
{5212}{}{. O ataque a um órgão vital bate o filho sobre}
{5213}{}{, derrubando a criança como um brinquedo}
{5214}{}{. Agora, essa criança nunca experimentará a vida de verdade.
{5215}{}{, infligindo um corte profundo}
{5216}{}{. O ataque derruba a criança e quebra a perna}
{5217}{}{, infligindo grandes danos à criança pequena}
{5218}{}{. A criança jovem olha para cima e começa a chorar}
{5219}{}{, que cega o jovem}
{5220}{}{, invadindo o nariz juvenil}
{5221}{}{. Um corte aparece acima dos olhos e o sangue começa a fluir livremente}
{5222}{}{, que abre um olho como uma uva explodindo. A criança parece desconcertada}
{5223}{}{causando cegueira. A criança pequena cai no chão
{5224}{}{, o golpe continua no pequeno cérebro}
{5225}{}{. A criança parece confusa e abalada}
{5226}{}{, batendo esse jovem alvo no chão}
#
# series 5300 - Super Mutants
#
{5300}{}{, machucando o poderoso mutante}
{5301}{}{, atingindo um ponto vital}
{5302}{}{, atingindo um ponto vital e derrubando o gigante no chão}
{5303}{}{. O mutante gigante olha ao redor por um momento, e depois cai no chão.
{5304}{}{. A cabeça explode como uma melancia gigante e sangrenta}
{5305}{}{, machucando gravemente o mutante poderoso}
{5306}{}{, fazendo com que o gigante passe um momento amaldiçoando o universo}
{5307}{}{, golpeando um nervo e forçando o gigante a agarrar seu braço com dor}
{5308}{}{. O golpe quebra o cotovelo e provavelmente não se sente bem demais}
{5309}{}{, quebrando o braço grosso e vomitando sangue mutante sobre o chão}
{5310}{}{, fazendo com que o gigante tropeça por um momento e depois colapse como uma árvore derrubada}
{5311}{}{, e galões de visceras tocam no chão}
{5312}{}{, enviando o gigante voando para o chão}
{5313}{}{. O mutante tropeça e cai, sua perna pouco capaz de apoiá-lo.
{5314}{}{, atingindo uma localização vital. O mutante amassa-se sob uma perna quebrada}
{5315}{}{. A dor de uma perna quebrada supera o poderoso gigante
{5316}{}{, quase cegando o mutante}
{5317}{}{, cegando o mutante agora furioso}
{5318}{}{, quase cegando o mutante, mas jogando-o fora do equilíbrio}
{5319}{}{. O mutante cego tropeça de volta, despreparado para o próximo ataque.
{5320}{}{, cegando o mutante agora inconsciente}
{5321}{}{. Os olhos do brilho mutante por um momento, e então a luz desaparece - permanentemente}
#
# series 5400 - Ghouls
#
{5400}{}{. O ghoul é surpreendido, e não consegue se defender contra este ataque}
{5401}{}{. Este golpe enterra esse ghoul}
{5402}{}{. A mão do ghoul atordoado voa aberta}
{5403}{}{, esgueirando sua armadura e atacando uma articulação crítica}
{5404}{}{, esgueirando sua armadura e cortando o braço}
{5405}{}{. O ghoul move o caminho errado no momento errado e perde o olho}
{5406}{}{. O ghoul não está vestindo nenhuma armadura}
{5407}{}{, e sem armadura, o ghoul está cego}
{5408}{}{, fazendo com que o fantasma pareça confundido nos últimos momentos}
#
# series 5500 - Brahmin
#
{5500}{}{, batendo o grande animal no chão}
{5501}{}{, impressionando ambos os cérebros e derrubando o animal gigante}
{5502}{}{. A vaca mutante dá um grito alto e assustado}
{5503}{}{, quebrando uma das pernas do Brahmin}
{5504}{}{, machucando gravemente a vaca mutante}
{5505}{}{, penetrando facilmente na espessura do animal gigante}
{5506}{}{, penetrando diretamente em ambos os corações da vaca mutante}
{5507}{}{, cegando ambos os conjuntos de olhos com um único golpe}
{5508}{}{, cegando as duas cabeças e deslizando a vaca mutante}
{5509}{}{, cegando completamente o brâmane e eliminando-o}
{5510}{}{, o grande mutante bovino tropeça por um momento}
{5511}{}{. O brâmane vibra com raiva}
{5512}{}{. O bravo mime com dor
{5513}{}{. O brahmin está mais chateado com este ataque áspero devastador}
#
# series 5600 - Radscorpions
#
{5600}{}{, enviando o Radscorpion voando sobre ele está de volta}
{5601}{}{, separando a cabeça da carapaça}
{5602}{}{, danificando seriamente a cauda}
{5603}{}{, colocando uma grande dor nas garras}
{5604}{}{. O golpe desliza entre as rachaduras da carapaça dura do Radscorpion}
{5605}{}{, golpeando a carapaça dura sem pausar}
{5606}{}{, passando pela armadura natural e batendo o Radscorpion sobre}
{5607}{}{. O Radscorpion não pode lidar com uma nova sensação, como falta de órgãos internos}
{5608}{}{, enviando o 'escorpião voando e paralisando algumas das pernas}
{5609}{}{. O ataque corta uma articulação desprotegida na perna, cortando-a}
{5610}{}{, ferindo gravemente e cegando a criatura mutante}
{5611}{}{, penetrando quase no cérebro. Fale sobre esmagar um erro}
{5612}{}{, quase penetrando no cérebro, mas cegando a criatura em vez disso}
{5613}{}{. O ataque é diabólico e muito sofisticado para essa simples criatura.
{5614}{}{. Se fosse humano, você iria jurar que está muito chateado}
{5615}{}{, batendo a pobre criatura sem sentido}
{5616}{}{, colocando o cérebro no chão}
#
# série 5700 - Ratos
#
{5700}{}{. O crânio do roedor faz vários sons insalubres}
{5701}{}{, esmagando o crânio do roedor como um saco de papel molhado}
{5702}{}{, e a pata esquerda agora parece um pouco plana}
{5703}{}{. A pata esquerda do rato é explodida}
{5704}{}{. A pata direita está fortemente danificada}
{5705}{}{, soprando a pata direita desativada}
{5706}{}{. O rato é gravemente ferido por este ataque}
{5707}{}{, ferindo gravemente o rato e derrubando}
{5708}{}{, espalhando o rato pelo chão}
{5709}{}{, danificando a perna direita}
{5710}{}{, colocando um grande buraco na perna esquerda}
{5711}{}{, fazendo alguns danos adicionais devido à localização sensível}
{5712}{}{, convocando essa criatura para o grande catador no céu}
#
# série 5800 - flutuadores
#
{5800}{}{, o flutuador cai no chão}
{5801}{}{, o flutuador cai no chão, aparentemente sem vida}
{5802}{}{, com sérias conseqüências para as criaturas continuou a existir}
{5803}{}{, impressionando a criatura suja}
{5804}{}{, atingindo um ponto sensível e deslizando o flutuador}
{5805}{}{. O golpe faz com que o flutuador treme violentamente em um spray de carmesim}
{5806}{}{, o golpe causando algum tipo de reação violenta na criatura}
{5807}{}{. O flutuador de repente explode em chamas}
{5808}{}{então ele empurra-se de forma selvagem e dura como uma surpresa de pudim}
{5809}{}{, com o golpe atingindo um ponto sensível}
{5810}{}{. A criatura é obviamente agitada}
#
# série 5900 - Centaurs
#
{5900}{}{, empurrado como um mau hábito, o centauro cai e está atordoado}
{5901}{}{como o golpe atinge um ponto crítico}
{5902}{}{, causando uma falha neurológica maciça}
{5903}{}{, impressionando-o com seu ataque violento}
{5904}{}{, aleijando o braço}
{5905}{}{atingindo um ponto crítico e aleijando o braço}
{5906}{}{, derrubando a criatura e danificando a perna}
{5907}{}{, deslumbrante o centauro, pois é derrubado com uma perna aleijada}
{5908}{}{, cegando uma cabeça}
{5909}{}{, surpreendendo o centauro. Apanha-se cegamente por um momento}
{5910}{}{, surpreende o centauro. Ele colapsa em uma pilha}
{5911}{}{, surpreendendo o centauro. Colapsa em uma pilha de goo}
{5912}{}{. O ataque não foi tão eficaz quanto poderia ter sido}
#
# série 6000 - Robôs
#
{6000}{}{, infligindo algum dano estrutural}
{6001}{}{, as faíscas voam e o robô fica momentaneamente fora de controle}
{6002}{}{, atingindo um componente crítico e forçando o robô fora de controle}
{6003}{}{, atingindo um componente crítico e causando um mau funcionamento maciço}
{6004}{}{. O robô tenta compensar}
{6005}{}{. O robô se esforça para compensar}
{6006}{}{, acertando alguma parte da chave e causando danos pesados}
{6007}{}{, infligindo danos estruturais pesados}
{6008}{}{, atingindo um componente crítico e causando danos graves}
{6009}{}{. O robô estremece sob este intenso ataque}
{6010}{}{, desmontando o robô}
{6011}{}{. O robô tenta compensar, mas falha, caindo no chão
{6012}{}{. O robô corre por baixo da pressão, caindo no chão
{6013}{}{, quebrando as lentes do sensor}
#
# série 6100 - Cães
#
{6100}{}{, batendo o cachorrinho no chão}
{6101}{}{, do outro lado do focinho}
{6102}{}{. O cachorro cai, mas ainda está respirando
{6103}{}{, o animal tossa um pingo de sangue}
{6104}{}{, danificando a perna}
{6105}{}{, danificando a perna. O animal tenta permanecer em pé, mas falha}
{6106}{}{. O animal cego uiva na dor
{6107}{}{, castrando o pobre animal}
#
# series 6200 - Manti
#
{6200}{}{, derrubando este inseto mutado}
{6201}{}{, que colapsa}
{6202}{}{. O manti questiona se deve continuar vivendo
{6203}{}{, aleijando o membro}
{6204}{}{, fazendo com que o Manti lambe suas feridas. Ele segura o membro estranhamente}
{6205}{}{, ignorando a armadura quitinosa}
{6206}{}{. O manti grita e arrepia deve ser desumano como}
{6207}{}{, o que faz com que o manti caia. Um membro está dobrado de forma estranha}
{6208}{}{, triturando as asas}
{6209}{}{, ignorando a armadura quitinosa e jogando o manti em torno}
{6210}{}{, cegando o inseto com um golpe preciso}
#
# série 6300 - Deathclaw
#
{6300}{}{. Mesmo esse animal parece perturbado por esse impressionante ataque.
{6301}{}{, passando pelas enormes garras para atacar o monstro. O Deathclaw agita e rosna
{6302}{}{. O resultado é um dano maciço aos olhos do Deathclaw}
#
# série 6400 - O Mestre
#
{6400}{}{, passando as defesas bio-orgânicas}
{6401}{}{, causando ao Maestro algum sofrimento sério}
{6402}{}{, passando as defesas bio-orgânicas e colocando a pressão sobre o Mestre}
{6403}{}{, impressionando o Mestre com um plano ofensivo sólido}
{6404}{}{, causando uma sobrecarga de proporções catastróficas nos sistemas do Mestrado}
{6405}{}{. O ataque contra o Mestre parece fazer menos dano do que deveria ter}
{6406}{}{. O golpe passa pelas defesas bio-orgânicas, realmente cegando o Mestre}
#
# series 6500 - The Player
#
{6500}{}{. Você vai ter uma dor de cabeça amanhã, se você viver tanto tempo}
{6501}{}{. Sua armadura não oferece proteção contra este golpe bem apontado}
{6502}{}{. Você sente a dor por apenas um momento, e então a escuridão leva você ...
{6503}{}{, ignorando sua armadura. O golpe bate-te nos pés}
{6504}{}{, o choque faz sua visão escurecer. Depois de um momento, você percebe que sua visão não retornou.
{6505}{}{. Você tem uma bela vista do seu corpo enquanto a sua cabeça viaja no ar}
{6506}{}{. Surpreendentemente, o dano não é pior do que o normal
{6507}{}{, impressionando você por um momento}
{6508}{}{. Sentir a dor}
{6509}{}{. O ataque deixa seu braço inútil}
{6510}{}{, passando por sua armadura. O golpe racha os ossos em seu braço como deadwood}
{6511}{}{, ignorando sua armadura. Seu braço agora pendura ao seu lado
{6512}{}{. O hematoma ficará bonito, e talvez as cicatrizes fiquem boas conversas na festa}
{6513}{}{, esmagando seus órgãos internos. Tudo o que você pode fazer é gurgle blood}
{6514}{}{, enviando cabeça sobre saltos}
{6515}{}{, enviando você voando e quebrando sua perna}
{6516}{}{, derretendo sua armadura. O golpe bate em você e machuca gravemente seu joelho}
{6517}{}{. A dor da sua perna quebrada envia você para a inconsciência
{6518}{}{. O doloroso golpe faz você se virar, mas faz pouco mais.
{6519}{}{. Azarado para você, também provoca perda imediata de visão}
{6520}{}{. Leve um momento para limpar o sangue dos seus olhos}
{6521}{}{, passando por sua armadura. Você fica atordoado quando percebe que você não pode ver mais}
{6522}{}{. Você sente uma sensação estranha na sua cabeça. Você percebe que é uma morte cerebral iminente
{6523}{}{, fazendo você se encolher}
{6524}{}{. Você taça sua virilha e cai no chão com dor}
{6525}{}{. A dor é suficiente para derrubá-lo. Ouch}
{6526}{}{. Não há palavras suficientes no universo para descrever a dor que você está sentindo neste momento}
