#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used in LOADSAVE.C
#
# (These MUST match "text message" enumeration on the top of LOADSAVE.C)
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

# System
{100}{}{CARREGAR jOGO} # Títulos
{101}{}{ESCOLHA UM ROTA DE CARGA RAPIDA}
{102}{}{SALVAR JOGO}
{103}{}{ESCOLHA UMA MANUTENCAO RAPIDA}
{104}{}{FEITO}
{105}{}{CANCEL}
{106}{}{Erro ao carregar a lista de jogos salvos!} # Linha 1
{107}{}{Salvar o diretorio do jogo:} # Linha 2
{108}{}{Nao existe ou esta corrompido.} # Linha 3
{109}{}{SALVAR JOGO}}
{110}{}{cARREGAR JOGO}
{111}{}{- VAZIO -}
{112}{}{- CORRIGIR ARQUIVO SALVO -}
{113}{}{- VERSAO ANTIGA -}
{114}{}{Vazio.}
{115}{}{Erro!}
{116}{}{versao antiga.}
{117}{}{JAN} # Meses
{118}{}{FEV}
{119}{}{MAR}
{120}{}{ABR}
{121}{}{MAI}
{122}{}{JUN}
{123}{}{JUL}
{124}{}{AGO}
{125}{}{SET}
{126}{}{OUT}
{127}{}{NOV}
{128}{}{DEZ}
{129}{}{Nivel}
{130}{}{DESCRICAO}
{131}{}{O jogo que vai salvar ja existe, sobrescrever?}
{132}{}{Erro ao salvar o jogo!} # Linha 1
{133}{}{Nao consegui salvar o jogo.} # Linha 2
{134}{}{Erro ao carregar o jogo!} # Linha 1
{135}{}{Nao consegui carregar o jogo.} # Linha 2
{136}{}{O arquivo do jogo Save é uma versao mais antiga.}
{137}{}{Mapa}

{140}{}{Jogo Salvo.}
{141}{}{Jogo Carregado.}
#
# Demo versões apenas
#
{200}{}{Desculpe, nao pode salvar ou carregar} # 1
{201}{}{na versao demo.} # 2

