#
#
#
#
#
{0}{}{Preferencias do jogo}
{1}{}{Configuracoes da tela}
{3}{}{Opcoes}

{50}{}{Configuracoes da tela}
{51}{}{Personalizado}
{52}{}{Largura}
{53}{}{Altura}
{54}{}{Concluido}
{55}{}{Cancelar}
{56}{}{Fallout deve reiniciar para aplicar as configuracoes.}
{57}{}{Voce gostaria de reiniciar Fallout agora?}
{58}{}{Verdadeiro}
{59}{}{Falso}
{60}{}{}


{100}{}{Res. Alta}
{101}{}{RESOLUCAO}
{102}{}{Cores}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Alterar a barra lateral da arte}
{107}{}{Inverter lista}
{108}{}{Windowed}
{109}{}{Definir a tecla de deslocamento}
{110}{}{Scaling X2}
{111}{}{Taxa de atualizacao}

{130}{}{Chave da janela}
{131}{}{Selecionar}
{132}{}{Nome}

{140}{}{Modo Graficos:}
{141}{}{Basico}
{142}{}{Modo Sfall DirectX 9:}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Vertex Hardware Processing:}
{149}{}{Shader Version 2.0:}

{150}{}{Painel de escala}
{151}{}{Nenhum}
{152}{}{Fit}
{153}{}{Preencher}

{154}{}{Filmes}
{155}{}{Splash}
{156}{}{Ajuda}
{157}{}{Morte}
{158}{}{End Slides}
{159}{}{Menu principal}

{200}{}{Sfall}
{201}{}{SCALE-TO: RES.}
{202}{}{MODO DX-9}
{203}{}{Desligado}
{204}{}{Fullscreen}
{205}{}{Janela}
{206}{}{GPU Blitting}
{207}{}{Esta configuracao nao tem efeito enquanto estiver no Modo Graficos Basicos.}

{250}{}{Ignorar Limite de deslocamento do PC}
{253}{}{intervalo de busca de caminho}
{254}{}{Normal}
{255}{}{Max}
{256}{}{Enable Fog Of War}
{257}{}{Visibilidade do nevoeiro}
{258}{}{Sombrio}
{259}{}{Mais brilhante}

{300}{}{PRESSIONE UMA TECLA ou ESC para cancelar.}

{500}{}{Configuracoes do Patch do Hi-Res.}
{501}{}{Configura a resolucao da tela, o modo de cor e a taxa de atualizacao para o modo FullScreen.}
{502}{}{Configure a saida de cores em tela cheia aqui.}
{503}{}{Configure a Taxa de atualizacao de tela cheia aqui. Defina isto como '0' para a configuracao padrao do driver.}
{504}{}{Personalizar a largura da tela cheia clicando na caixa do número.}
{505}{}{Personalizar a altura da tela inteira clicando na caixa do número.}
{506}{}{Ativar ou desativar o modo de janela.}
{507}{}{No Modo Janela, esta é a tecla que voce mantém pressionada ao usar o mouse para rolar os mapas do Jogo e do Mundo.}
{508}{}{Pressione o botao vermelho para selecionar uma tecla diferente. Ou clique na caixa do número para editar o código da chave virtual do Windows.}
{509}{}{O nome da chave atualmente selecionada.}
{510}{}{Enable X2 scaling. Isso também aumentara a resolucao de min para 1280x960. Com o modo Janela exigindo mais espaço para o quadro.}
{511}{}{Enable ou Disable Fog Of War. Para obter melhores resultados, este deve ser ativado antes de entrar em um mapa pela primeira vez.}
{512}{}{Ajuste o nivel da luz e o mouse 'olhe a visibilidade dos pisos, paredes e cenarios sob o nevoeiro.}
{513}{}{Os pisos, paredes e cenario sempre estarao visiveis e o mouse "olhar" funcionara normalmente.
{514}{}{Pisos, paredes e paisagens serao escurecidos e nao respondem ao mouse "olhe" até descoberto.}
{515}{}{Quando ativado, o deslocamento do Character Player é ilimitado. Isso funciona bem se Fog Of War ativado.}
{516}{}{Aumentar o número de nós de busca para estender a distância de busca do caminho. 20 niveis em incrementos de nó de 2000.}
{517}{}{nó de pesquisa de 2000 caminhos (valor original). Nota: cada nivel requer mais 156,25 KB de memória.}
{518}{}{40 000 nós de busca de caminho. Nota: requer 3200000 bytes (3125 KB) de memória.}
{519}{}{Ajusta como determinadas telas sao exibidas.}
{520}{}{Tamanho original.}
{521}{}{Esticado para ajustar o tamanho da tela enquanto mantém a relacao de aspecto original.}
{522}{}{Esticado para preencher a tela. Nota: Um espaço permanecera na parte inferior da tela se as legendas estiverem ativadas.}
{523}{}{Clique abaixo para rodar as opcoes da barra lateral da interface no jogo.}
{524}{}{Aplicar quaisquer alteracoes e sair.}
{525}{}{Sair sem salvar.}

